name: Chromatic (Storybook)

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    chromatic:
        name: Run Chromatic (Storybook)
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_STORYBOOK_PROJECT_TOKEN }}
                  onlyChanged: true
